window:

#    decorations: "none"

    background_opacity: 0.8
    live_config_reload: true
    dimensions:
      columns: 120
      lines: 30

shell:
  program: C:/Program Files/PowerShell/7/pwsh.exe

working_directory: C:\Users\meleehao\

font:

  size: 12


  normal:

#    family: Sarasa Term SC Semibold 

    family: Sarasa Term SC 

    style: Semibold Italic


  bold:

    family: Sarasa Term TC
    style: Semibold Italic

  italic:

    family: Sarasa Term SC Semibold
    style: Semibold Italic
colors:

  primary:

    foreground: '0xeeeeec'


  normal:

     black:   '0x2e3436'

     red:     '0xcc0000'

     green:   '0x73d216'

     yellow:  '0xedd400'

     blue:    '0x3465a4'

     magenta: '0x75507b'

     cyan:    '0x06989a'

     white:   '0xd3d7cf'


  bright:

     black:   '0x2e3436'

     red:     '0xef2929'

     green:   '0x8ae234'

     yellow:  '0xfce94f'

     blue:    '0x729fcf'

     magenta: '0xad7fa8'

     cyan:    '0x34e2e2'

     white:   '0xeeeeec'
#

